### ISSUE TITLE
After Changing Charts Once, Chart Cannot be Updated Again.

### ISSUE THREAD

**Issue by noonononnonnoo** [PrincessMtH/SNIFF#3]
So, I made a chart over Roses, and when I played the new chart, I noticed a few things wrong with it. So, I went back into the FLP, changed what I noticed was wrong, and I re-exported the .json files in the same directory. But, when I went back into the game, and re-played those changes were still in the charts! I couldn't change it, I even tried deleting the original .json files and making a new FLP, yet somehow the changes stayed even though it's a completely new FLP and the original .json files aren't there anymore, the issues stayed.
(And this isn't important since this has happened multiple times with different copies and different versions of Funkin',but with this specific case I used Modding +.)

**Comment by PrincessMtH** [comment]
usually when this happens, it's just because i forgot to save the FLP before trying again, or i had stuff in the wrong patterns! this is an issue that really can only happen if something went wrong while saving the file, because there's no other way SNIFF can access like, an old version of it. so there must be something up with the FLP itself.
maybe you forgot to save, maybe you put it on the wrong pattern, maybe you have multiple channels with an old version on one of them, maybe you're just using the wrong FLP... could you check to make sure it isn't any of those and then report back? thanks!

**Comment by noonononnonnoo** [comment]
Yes, I have checked multiple times and none of  those are the issue.

**Comment by PrincessMtH** [comment]
can you share the file in question?
